FROM eclipse-temurin:17 as builder

WORKDIR /app
COPY . ./
RUN ./mvnw clean install

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.0.0

# update packages to latest state, and install TAR for k8s copy command use
# RUN microdnf update -y --nodocs && microdnf install -y tar && microdnf clean all && rm -rf /var/cache/yum/*

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=eclipse-temurin:17 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN echo "app:x:1000:1000:app user:/nonexistent:/bin/false" >>/etc/passwd && echo "app:x:1000:" >>/etc/group

COPY --from=builder /app/target/devtunnel-*-SNAPSHOT.jar /app/service.jar

USER 1000:1000
CMD [ "java", "-XX:MaxRAMPercentage=70", "-XshowSettings:vm", "-Dspring.profiles.active=kubernetes,tst", "-jar", "/app/service.jar" ]
